# Generated by Django 4.2.7 on 2023-12-04 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('GROWER_NO', models.AutoField(primary_key=True, serialize=False)),
                ('SURNAME', models.CharField(max_length=255)),
                ('NAME_INITIALS', models.CharField(max_length=10)),
                ('NATIONAL_ID', models.CharField(max_length=20)),
                ('TEL_NO', models.CharField(max_length=15)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('POSTAL_ADDRESS1', models.CharField(max_length=255)),
                ('POSTAL_ADDRESS2', models.CharField(blank=True, max_length=255, null=True)),
                ('FARM_NAME', models.CharField(max_length=255)),
                ('AREA_PROVINCE', models.CharField(max_length=50)),
                ('CURRENT_REG', models.CharField(max_length=50)),
                ('NEXT_REG', models.CharField(max_length=50)),
                ('CONTRACTOR', models.CharField(max_length=255)),
                ('HECTARES', models.FloatField()),
                ('PROVINCE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOAN_SCHEME', models.CharField(max_length=255)),
                ('INPUT_TYPE', models.CharField(max_length=255)),
                ('PRODUCT_CODE', models.CharField(max_length=20)),
                ('DESCRIPTION', models.TextField()),
                ('PACKAGING_UNITS', models.CharField(max_length=20)),
                ('UNITS_ISSUED', models.FloatField()),
                ('CURRENCY', models.CharField(max_length=10)),
                ('UNIT_PRICE', models.FloatField()),
                ('QTY_ISSUED', models.FloatField()),
                ('INVOICE_AMOUNT', models.FloatField()),
                ('CREDITOR_NO', models.CharField(max_length=20)),
                ('RECEIPT_NO', models.CharField(max_length=20)),
                ('CHAIRMAN', models.CharField(max_length=255)),
                ('AREA_MGR', models.CharField(max_length=255)),
                ('COLLECTION_POINT', models.CharField(max_length=255)),
                ('GROWER_NO', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.client')),
            ],
        ),
    ]
