# Generated by Django 4.2.7 on 2023-12-04 13:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('GROWER_NO', models.CharField(default=uuid.uuid4, max_length=36, primary_key=True, serialize=False, unique=True)),
                ('SURNAME', models.CharField(max_length=255)),
                ('NAME_INITIALS', models.CharField(max_length=10)),
                ('NATIONAL_ID', models.CharField(max_length=20)),
                ('TEL_NO', models.CharField(max_length=15)),
                ('EMAIL', models.EmailField(max_length=255)),
                ('POSTAL_ADDRESS1', models.CharField(max_length=255)),
                ('POSTAL_ADDRESS2', models.CharField(max_length=255)),
                ('FARM_NAME', models.CharField(max_length=255)),
                ('AREA_PROVINCE', models.CharField(max_length=50)),
                ('CURRENT_REG', models.CharField(max_length=50)),
                ('NEXT_REG', models.CharField(max_length=50)),
                ('CONTRACTOR', models.CharField(max_length=255)),
                ('HECTARES', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PROVINCE', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('username', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LoanStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LOAN_SCHEME', models.CharField(max_length=150)),
                ('INPUT_TYPE', models.CharField(max_length=150)),
                ('PRODUCT_CODE', models.CharField(max_length=20)),
                ('DESCRIPTION', models.TextField(max_length=255)),
                ('PACKAGING_UNITS', models.CharField(max_length=20)),
                ('UNITS_ISSUED', models.FloatField()),
                ('CURRENCY', models.CharField(max_length=10)),
                ('UNIT_PRICE', models.FloatField()),
                ('INVOICE_AMOUNT', models.FloatField()),
                ('CREDITOR_NO', models.CharField(max_length=20)),
                ('RECEIPT_NO', models.CharField(max_length=20)),
                ('CHAIRMAN', models.CharField(max_length=255)),
                ('AREA_MGR', models.CharField(max_length=255)),
                ('COLLECTION_POINT', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_statements', to='core.client')),
            ],
        ),
    ]
