# Generated by Django 4.2.7 on 2023-12-04 08:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='id',
            field=models.BigAutoField(auto_created=True, default=django.utils.timezone.now, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='GROWER_NO',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='client',
            name='POSTAL_ADDRESS2',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanstatement',
            name='GROWER_NO',
            field=models.CharField(max_length=7),
        ),
    ]
