# Generated by Django 4.2.7 on 2023-12-04 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_client_id_alter_client_grower_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='GROWER_NO',
            field=models.CharField(max_length=7, validators=[django.core.validators.MaxLengthValidator(limit_value=7)]),
        ),
    ]
